version: '3.8'
services:
  eval:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: /bin/bash
    command: -c "chmod +x eval.sh && ./eval.sh ${TARGET}"
    stdin_open: true
    tty: true
