name: Evaluate Solutions
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      folder:
        description: 'Folder/File to evaluate (e.g. lab5, lab5/ora1-ttc, lab5/ora1-ttc/ttc.cpp)'
        required: true
        default: 'lab6'
permissions:
  pull-requests: write
  contents: read
jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y time bc python3
      - name: Make eval.sh executable
        run: chmod +x eval.sh
      - name: Run evaluation
        id: eval
        run: |
          FOLDER="${{ github.event.inputs.folder || 'lab6' }}"
          ./eval.sh -g "$FOLDER" | tee results.md
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const results = fs.readFileSync('results.md', 'utf8');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: results
            });
